os: osx
osx_image: xcode11.2
language: objective-c

before_cache:
  - brew cleanup

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  homebrew:
    casks:
    - osxfuse

script:
  - set -o pipefail
  - xcodebuild -project logfuse.xcodeproj -scheme logfuse -destination platform\=macOS build | xcpretty

